# -*- coding: utf-8 -*-
"""Deliverable-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tB-MVYBOWyyzy_e9aX2lVeUOs4GpV1sy
"""

from pprint import pprint
import requests
from bs4 import BeautifulSoup
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline

class URLValidator:
    """
    A production-ready URL validation class that evaluates the credibility of a webpage
    using multiple factors: domain trust, content relevance, fact-checking, bias detection, and citations.
    """

    def __init__(self):
        self.serpapi_key = "cQE4uiHtftGEvznm65DA4di1"

        # Load models once to avoid redundant API calls
        self.similarity_model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
        self.fake_news_classifier = pipeline("text-classification", model="mrm8488/bert-tiny-finetuned-fake-news-detection")
        self.sentiment_analyzer = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment")

    def fetch_page_content(self, url: str) -> str:
        """ Fetches and extracts text content from the given URL. """
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")

            paragraphs = [p.text.strip() for p in soup.find_all("p")]
            content = " ".join(paragraphs)

            if not content:
                print(f"[ERROR] No meaningful content extracted from {url}")
            return content if content else ""
        except requests.RequestException as e:
            print(f"[ERROR] Failed to fetch content from {url}: {e}")
            return ""

    def get_domain_trust(self, url: str, content: str) -> int:
        """ Computes the domain trust score based on available data sources. """
        trust_scores = []
        if content:
            try:
                trust_scores.append(self.get_domain_trust_huggingface(content))
            except Exception as e:
                print(f"[ERROR] Trust score calculation failed: {e}")

        return int(sum(trust_scores) / len(trust_scores)) if trust_scores else 50

    def get_domain_trust_huggingface(self, content: str) -> int:
        """ Uses a Hugging Face fake news detection model to assess credibility. """
        if not content:
            return 50
        result = self.fake_news_classifier(content[:512])[0]
        return 100 if result["label"] == "REAL" else 30 if result["label"] == "FAKE" else 50

    def compute_similarity_score(self, user_query: str, content: str) -> int:
        """ Computes semantic similarity between user query and page content. """
        if not content or not user_query:
            return 0
        query_embedding = self.similarity_model.encode(user_query)
        content_embedding = self.similarity_model.encode(content[:1000])  # Use first 1000 chars
        similarity = util.pytorch_cos_sim(query_embedding, content_embedding).item()
        return int(similarity * 100)

    def check_facts(self, content: str) -> int:
        """ Cross-checks extracted content with a placeholder logic for fact-checking. """
        if not content:
            return 50
        # Placeholder fact-checking logic
        fact_keywords = ["verified", "confirmed", "fact", "official", "proven"]
        score = 80 if any(word in content.lower() for word in fact_keywords) else 40
        return score

    def check_google_scholar(self, url: str) -> int:
        """ Checks Google Scholar citations using SerpAPI. """
        serpapi_key = self.serpapi_key
        params = {"q": url, "engine": "google_scholar", "api_key": serpapi_key}
        try:
            response = requests.get("https://serpapi.com/search", params=params)
            response.raise_for_status()
            data = response.json()
            citations = len(data.get("organic_results", [])) * 10
            return max(35, min(citations, 100))
        except Exception as e:
            print(f"[ERROR] Google Scholar lookup failed: {e}")
            return 35

    def detect_bias(self, content: str) -> int:
        """ Uses NLP sentiment analysis to detect potential bias in content. """
        if not content:
            return 50
        sentiment_result = self.sentiment_analyzer(content[:512])[0]
        return 100 if sentiment_result["label"] == "POSITIVE" else 50 if sentiment_result["label"] == "NEUTRAL" else 30

    def get_star_rating(self, score: float) -> tuple:
        """ Converts a score (0-100) into a 1-5 star rating. """
        stars = max(1, min(5, round(score / 20)))
        return stars, "⭐" * stars

    def generate_explanation(self, domain_trust, similarity_score, fact_check_score, bias_score, citation_score, final_score) -> str:
        """ Generates a human-readable explanation for the score. """
        reasons = []
        if domain_trust < 50:
            reasons.append("The source has low domain authority.")
        if similarity_score < 50:
            reasons.append("The content is not highly relevant to your query.")
        if fact_check_score < 50:
            reasons.append("Limited fact-checking verification found.")
        if bias_score < 50:
            reasons.append("Potential bias detected in the content.")
        if citation_score < 30:
            reasons.append("Few citations found for this content.")

        return " ".join(reasons) if reasons else "This source is highly credible and relevant."

    def rate_url_validity(self, user_query: str, url: str) -> dict:
        """ Main function to evaluate the validity of a webpage. """
        content = self.fetch_page_content(url)
        if not content:
            print("[WARNING] No content extracted. Returning default scores.")

        domain_trust = self.get_domain_trust(url, content)
        similarity_score = self.compute_similarity_score(user_query, content)
        fact_check_score = self.check_facts(content)
        bias_score = self.detect_bias(content)
        citation_score = self.check_google_scholar(url)

        final_score = (
            (0.3 * domain_trust) +
            (0.3 * similarity_score) +
            (0.2 * fact_check_score) +
            (0.1 * bias_score) +
            (0.1 * citation_score)
        )

        stars, icon = self.get_star_rating(final_score)
        explanation = self.generate_explanation(domain_trust, similarity_score, fact_check_score, bias_score, citation_score, final_score)

        return {
            "raw_score": {
                "Domain Trust": domain_trust,
                "Content Relevance": similarity_score,
                "Fact-Check Score": fact_check_score,
                "Bias Score": bias_score,
                "Citation Score": citation_score,
                "Final Validity Score": final_score
            },
            "stars": {
                "score": stars,
                "icon": icon
            },
            "explanation": explanation
        }

# Instantiate the URLValidator class
validator = URLValidator()

# Define user prompt and URL
user_prompt = "Evaluate the approval of a weight loss drug for heart disease treatment by Australia's medicines regulator."
url_to_check = "https://www.racgp.org.au/afp/2017/july/pharmacotherapy-for-obesity"

# Run the validation
result = validator.rate_url_validity(user_prompt, url_to_check)

# Print the results
import json
print(json.dumps(result, indent=2))